# Generated by Django 4.2.5 on 2023-10-03 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffreg',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='STAFF ID')),
                ('staff_name', models.CharField(max_length=25, verbose_name='STAFF NAME')),
                ('dob', models.DateField(verbose_name='DATE OF BIRTH')),
                ('address', models.CharField(max_length=50, verbose_name='ADDRESS')),
                ('phone_number', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: ' +91 '. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('designation', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('pwd', models.CharField(max_length=25, verbose_name='PASSWORD')),
                ('pic', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Studentreg',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='STUDENT ID')),
                ('student_name', models.CharField(max_length=25, verbose_name='STUDENT NAME')),
                ('dob', models.DateField(verbose_name='DATE OF BIRTH')),
                ('address', models.CharField(max_length=50, verbose_name='ADDRESS')),
                ('program', models.IntegerField()),
                ('department', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('pwd', models.CharField(max_length=25, verbose_name='PASSWORD')),
                ('pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
