# Generated by Django 4.2.5 on 2023-10-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_staffreg_studentreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='dob',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='pwd',
            field=models.CharField(max_length=25, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Student Id'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='student_name',
            field=models.CharField(max_length=25, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.department'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.program'),
        ),
    ]
