# Generated by Django 4.2.5 on 2023-10-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_department_program_alter_studentreg_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('des_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Designation Id')),
                ('des_name', models.CharField(max_length=50, verbose_name='Designation')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.AddField(
            model_name='department',
            name='d_id',
            field=models.IntegerField(default=101, primary_key=True, serialize=False, verbose_name='Department Id'),
        ),
        migrations.AddField(
            model_name='program',
            name='p_id',
            field=models.IntegerField(default=100, primary_key=True, serialize=False, verbose_name='Program Id'),
        ),
        migrations.AlterField(
            model_name='department',
            name='d_name',
            field=models.CharField(max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='program',
            name='p_name',
            field=models.CharField(max_length=50, verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.designation'),
        ),
    ]
