# Generated by Django 4.2.5 on 2023-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_alter_department_d_id_alter_designation_des_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='des_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Designation Id'),
        ),
        migrations.AlterField(
            model_name='program',
            name='p_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Program Id'),
        ),
    ]
