# Generated by Django 4.2.5 on 2023-10-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_alter_department_d_id_alter_designation_des_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffreg',
            old_name='designation',
            new_name='des_id',
        ),
        migrations.RenameField(
            model_name='studentreg',
            old_name='department',
            new_name='d_id',
        ),
        migrations.RenameField(
            model_name='studentreg',
            old_name='program',
            new_name='p_id',
        ),
    ]
