# Generated by Django 4.2.5 on 2023-10-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_alter_department_d_id_alter_designation_des_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='d_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='des_name',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='p_name',
            new_name='program',
        ),
        migrations.AlterField(
            model_name='department',
            name='d_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='des_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='p_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='des_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.department'),
        ),
    ]
