# Generated by Django 4.2.5 on 2023-10-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_rename_d_name_department_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='des_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.designation'),
        ),
    ]
