# Generated by Django 4.2.5 on 2023-10-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_alter_staffreg_des_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Department Id'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='des_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Designation Id'),
        ),
        migrations.AlterField(
            model_name='program',
            name='p_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Program id'),
        ),
    ]
