# Generated by Django 4.2.5 on 2023-10-04 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_alter_department_d_id_alter_designation_des_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='phone_number',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: ' +91 '. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='phone_number',
            field=models.CharField(default='', max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: ' +91 '. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
    ]
